const EXAM_TYPES=new Set(["weekly","monthly","midterm","final","school","joint","mock1","mock2","mock3","other"]);
export function examComparisonCategory(value){const type=typeof value==="string"?value:value?.type;if(type==="joint"||type==="school")return"joint_school";if(["mock1","mock2","mock3"].includes(type))return"mock";return EXAM_TYPES.has(type)?type:"other";}
function normalizedComparison(exam){const comparison=exam?.comparison||{};return{series:String(comparison.series||"").trim(),level:String(comparison.level||"").trim()};}
export function comparisonEligibility(latest,previous){if(!latest||!previous)return{status:"baseline",reason:"还没有第二次可以直接比较的考试"};if(latest.attendance==="absent"||latest.status==="absent")return{status:"not_comparable",reason:"这次考试标记为缺考，暂不直接比较"};if(previous.attendance==="absent"||previous.status==="absent")return{status:"not_comparable",reason:"对比的考试标记为缺考，暂不直接比较"};if(examComparisonCategory(latest)!==examComparisonCategory(previous))return{status:"not_comparable",reason:"考试类别不同，暂不直接比较"};const a=normalizedComparison(latest),b=normalizedComparison(previous),sameSeries=Boolean(a.series&&b.series&&a.series===b.series),sameLevel=Boolean(a.level&&b.level&&a.level===b.level);if(sameSeries&&sameLevel)return{status:"comparable",strength:"strong",reason:"同一考试系列和范围"};if(sameLevel)return{status:"comparable",strength:"standard",reason:"考试类别相同，比较范围相同"};if(a.level||b.level)return{status:"comparable",strength:"limited",reason:"考试类别相同，但比较范围信息不同或不完整"};return{status:"comparable",strength:"standard",reason:"考试类别相同"};}
export function compareExamsChronologically(a,b){return String(b?.date||"").localeCompare(String(a?.date||""))||String(b?.createdAt||"").localeCompare(String(a?.createdAt||""))||String(a?.id||"").localeCompare(String(b?.id||""));}
export function sortExamsChronologically(exams=[]){return[...exams].sort(compareExamsChronologically);}
export function latestExam(exams=[]){return sortExamsChronologically(exams)[0]||null;}
export function comparableRanking(a,b){if(!a||!b)return false;if((a.contextId||"")&&(b.contextId||""))return a.scope===b.scope&&a.contextId===b.contextId&&(a.basis||"final_score")===(b.basis||"final_score");return a.scope===b.scope&&(a.labelSnapshot||a.label||"")===(b.labelSnapshot||b.label||"")&&(a.basis||"final_score")===(b.basis||"final_score");}
export function percentile(rank,participants){if(!Number.isInteger(rank)||!Number.isInteger(participants)||rank<1||participants<rank)return null;return Math.round((rank/participants)*1000)/10;}
